language: node_js
node_js:
- '9.5.0'
env:
  global:
  - secure: X/jjrOivvcswBGo0MB1/RBeAvk5uZLEKMSPUyOBFyuW6IN5ZHoObb4qPIl1fLiAzbycLzkgXCRRm5LZfv1CKb4I86ICs7oJYq8wn/PTNQRTjP8XTwW+OgZdLWCEPg24YrFIwsn3NIWbsMXujI9ZQYqaUZOf/0Dm9XPsZ5gs7vh9OyzoMQJjLvOsbSlomP73us16eTTdyDCs8POhFnv9qCBDfpjAIsC5ouXop0mIObSUkN6DAgvY9IZJNXRqxnKLhrp1q5WXbz6RRNCsMV8Z8890tX7s1FS4jkkWWqGmdkGTPMFTOvWGgbZzYA1n0E/3aqvIaEvPUZTKgBDDwJaioq0lh8EloFKA79B+HYL9ykEX1vjmf916tC5VZli6Ua46UqQ0nWBtz9sKZ+2deXHzT9u8osJSV565wXWxexE4xNsGLOzOyYNmlmjWh6XrAGyYGVTnm475ZmawRcJZ8gQF2VJuKixWQ++QVIljy1GRgvlojgmAR4MytPp7bbtD5FoHo7sjWuymKx4BRbvR1IF0ZQokKInMuKM8pOMPyT3moUnW+evYhquHW3sjEyryYu5TjDR7LXAKf/gsPN9FPmNLFlqVcC1N0xsm1y3yD0ytFZBWzO8TiSJemeiPG6Xwz3E7yHOO6R+ryYyTb3AhIK5KQnxUIGHxpqcbGDMwWNqS3WLA=
  - secure: zzQ+/cSgN3zi7kN05zKVIPTNp0WYijZagtWRWff0DTpf+dlAKXalnYGT6pHRtNgyC0vS2JHms9fbsVVodk/L0Jv+RvYdPbSi4MEMuEw8YqLVjypQdNnGMBmk+08jUVOu9T4YHQa3BTZ9h8CbigF4VwGLZusa6afkPITf4YVPor3974YRgRP8umxglLqbmjvBaZoB5X4iqCLI2NYw+WP/uMJAVBr+XUPrK4JvKh0VQklhZV6h8P+rCo14898fOR6TO9RAGPEKCwuEvBpbfJZhvqVgawxl1mVYd9dHT4JzkimYATGVJG/UDGQ8kTnmugJcsUrZmFv+gGjBylc/GFVsmFHCIueTYHf4lb8NehBspKTy+VzKnDCq9vuIlAO02X9AB+9/a7M3wCdLCi6AVVCKYN8BlpCUXTEvKAj4g750wZFQqRI2osPPWbJsnBF9EuDvdrBOchSCOx8AeQ+v3+jcZjDg+4X2ZsCg5ewJIOnekKC4r2pf2PdDmG2/t1sKvbTfdH0hXusA12bGBnJNnt9KghlE5w0PhIW5PfnVkgcIr1mOtkWPCqwb+QcVVAx6GqZOQmH3sEUoDwTGVS5S1fb6WrlT6TTNdenP/AZ7SRVBk+oPyBzGUKxGLBy2fQMBIuOBAscHA3k6xSNInEzSUrR75E40iE/vxIVN1Teuq+8VSYw=
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: D6WbMJERwDFpcnMVb2FZLEuphte5drFVW/N+P71+RmVK3tsVoFevP1exIOtZlS6row3EBRR7pUJgFuQtvKu+8IDTgbena95z8nFsVdJtphptfNEcD7OUg3f9R8nhB7V2q0yFhRp6ax0LZN8SvFFLmDGFTJHh/XDhYAL7BZk3swuRBEncZawy2C0S2m7V5soYPArA9GrqnvRm+EPSFBylgxjx3tbq/7b6gwsxAVsjfdF7L6B+4zp/bvkZOBryATOa8oWpXZ7owsbuMS5NKIzN0nSrBHGygZDXUcvlYSaZhcdb8QiGrNdgXNAK+N48XfpAhscbG2u272Iinp5xtu+nOsRXJ0RupbfLlH3keEO1Cb5IaMMJ6pSZ1De3Vs9k/V79uvFk4lv8EZNpaOZmd3N5lmfNl/2vAgWtkn9bQoFanlsDKOoWvF47kY5qcIaHFH3W4wI1iirV58l4PrOwl4dHRCHOs9kyMNV4dWpFIzB/lTDKJasjlFBh4LxPd2yI52RgpJFWwPJA66de88XqEKpN+xPNsq8s9ZClVS8NKPwxR/pL/8rpvDt5fPJWL/wh8mkmgkhM4m/KgJinawycUHxuzydFwKkGSSUDrKtRpWq06J8N9F/yWHwfc2rvhfYnsyq9UMfkPV68xaQIjOMHxM5EyttJd/TpHIhwEQNbSa5IAAo=
  on:
    repo: plepers/nanogl-pbr
    branch: master
