name: Trigger docs re-build

on:
  push:
    branches:
      - 'next/3.0'

jobs:
  trigger_docs:
    name: Trigger docs re-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Build docs
        run: |
          npm install
          npm run docs

      - name: Commit and push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'update: docs (via GHAction)'
          author_email: 'evan.martiin29@gmail.com'
          author_name: 'evanmartiin'
          branch: 'next/3.0'

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONS_KEY }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'evanmartiin',
              repo: 'nanogl-docs',
              workflow_id: 'main.yml',
              ref: 'main'
            })
